version: '3.8'

services:
  deployer:
    image: igoralcantara/deployer:0.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE=deployments
    networks:
      - minha_rede
    depends_on:
      - rabbitmq
    deploy:
      replicas: 1

networks:
  minha_rede:
    external: true